### ISSUE TITLE
使用dubbo2.8.4 ，后端系统出现异常，请稍后再试！

### ISSUE THREAD

**Issue by yanf820** [dubboclub/dubbokeeper#108]
使用dubbo2.8.4，ui和server都启动了，但是点击monitor依然会提示异常  
![](http://i.imgur.com/PVALDGh.jpg)  

```
Caused by: com.alibaba.dubbo.remoting.RemotingException: message can not send, because channel is closed . url:dubbo://10.1.36.82:20884/com.dubboclub.dk.storage.StatisticsStorage?anyhost=true&application=common-monitor&check=false&client=netty4&codec=dubbo&dubbo=2.8.4&generic=false&heartbeat=60000&interface=com.dubboclub.dk.storage.StatisticsStorage&logger=slf4j&methods=storeStatistics,queryMethodMonitorOverview,queryApplicationOverview,queryStatisticsForMethod,queryApplications,queryServiceByApp,queryApplicationInfo,queryServiceOverview&owner=lashou&pid=1388&revision=1.0.1&side=consumer&timeout=10000&timestamp=1493112534165
	at com.alibaba.dubbo.remoting.transport.AbstractClient.send(AbstractClient.java:268) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.remoting.transport.AbstractPeer.send(AbstractPeer.java:51) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeChannel.request(HeaderExchangeChannel.java:112) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeClient.request(HeaderExchangeClient.java:91) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.protocol.dubbo.ReferenceCountExchangeClient.request(ReferenceCountExchangeClient.java:81) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:96) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77) ~[dubbo-2.8.4.jar:2.8.4]
	... 42 common frames omitted
```

请问这是timeout问题还是dubbo版本问题呢？    谢谢！

**Comment by yanf820** [comment]
不好意思，是我自己的问题，因为本地开的有wifi热点，导致本机ip问题，所以上面的错误是访问我本机ip不通，关掉wifi热点就好
