### ISSUE TITLE
zookeeper集群

### ISSUE THREAD

**Issue by kitikousei** [dubboclub/dubbokeeper#109]
zookeeper集群在dubbokeeper-service中怎么配置

**Comment by qct** [comment]
和使用dubbo服务一样：
```<dubbo:registry address="zookeeper://10.20.153.10:2181?backup=10.20.153.11:2181,10.20.153.12:2181" />```

or

```dubbo.registry.address=zookeeper://10.20.153.10:2181?backup=10.20.153.11:2181,10.20.153.12:2181```

**Comment by kitikousei** [comment]
Caused by: com.alibaba.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2017-05-07 00:00:03.115, end time: 2017-05-07 00:00:04.136, client elapsed: 0 ms, server elapsed: 1021 ms, timeout: 1000 ms, request: Request [id=435797, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=collect, parameterTypes=[class com.alibaba.dubbo.common.URL], arguments=[count://192.168.17.13:20981/com.sanchro.java.hgame.dubbo_api.user.service.DubboUserService/userLogin?application=hgame_provider&concurrent=0&consumer=192.168.17.13&elapsed=615&failure=0&input=55217&interface=com.sanchro.java.hgame.dubbo_api.user.service.DubboUserService&max.concurrent=1&max.elapsed=14&max.input=401&max.output=0&method=userLogin&output=0&success=139&timestamp=1494086401068], attachments={path=com.alibaba.dubbo.monitor.MonitorService, interface=com.alibaba.dubbo.monitor.MonitorService, version=0.0.0}]], channel: /192.168.17.13:2741 -> /192.168.17.13:20980

 生产开启监控之后，发现日志里有大量的超时日志。但应用的调用还是正常的。不知道是不是配置问题导致资源不足，还是其他什么原因。
其次，上生产的时候，启动monitor-mysql，命令行会提示资源不够的情况（忘记截图了），且应用都无法正常调用。用其他终端登上来看，内存和cup都在一个相对较低的数值范围。

**Comment by kitikousei** [comment]
另外附上命令行提示资源不够时，日志情况
19:55:32 190903 [New I/O worker #2] WARN  warn(NettyHelper.java:90)   -  [DUBBO] An exception was thrown by a user handler while handling an exception event ([id: 0xdd599f80, /192.168.17.13:41917 => /192.168.17.13:20981] EXCEPTION: com.alibaba.dubbo.remoting.ExecutionException: class com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler error when process received event .), dubbo version: 2.5.3, current host: 192.168.17.13
com.alibaba.dubbo.remoting.ExecutionException: class com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler error when process caught event .
        at com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler.caught(AllChannelHandler.java:67)
        at com.alibaba.dubbo.remoting.transport.AbstractChannelHandlerDelegate.caught(AbstractChannelHandlerDelegate.java:44)
        at com.alibaba.dubbo.remoting.transport.AbstractChannelHandlerDelegate.caught(AbstractChannelHandlerDelegate.java:44)
        at com.alibaba.dubbo.remoting.transport.AbstractPeer.caught(AbstractPeer.java:127)
        at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.exceptionCaught(NettyHandler.java:112)
        at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.exceptionCaught(NettyCodecAdapter.java:165)
        at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:525)
        at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:48)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:148)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:713)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:949)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1360)
        at com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler.caught(AllChannelHandler.java:65)
        ... 19 more

**Comment by kitikousei** [comment]
dubbo-framework/DUBBO.log
出现如下日志：

2017-05-07 00:37:44.458 [NettyServerWorker-thread-9] WARN  c.a.d.c.t.s.AbortPolicyWithReport -  [DUBBO] Thread pool is EXHAUSTED! Thread Name: DubboServerHandler-192.168.17.13:20980, Pool Size: 200 (active: 200, core: 200, max: 200, largest: 200), Task: 894668 (completed: 894468), Executor status:(isShutdown:false, isTerminated:false, isTerminating:false), in dubbo://192.168.17.13:20980!, dubbo version: 2.5.3, current host: 127.0.0.1

这个200个线程池怎么会用完了，还有，从哪里能配置这个线程池的大小呢

**Comment by kitikousei** [comment]
@qct

**Comment by kitikousei** [comment]
dubbo-mysql.properties配置文件里，我已经把线程数增加到400了。register信息里面，线程数也生效了。但是系统运行一段时间之后，线程又用完了。
dubbo.protocol.threads=400

Monitor界面点开也显示：后端系统出现异常，请稍后再试！

ps：重启dubbokeeper，Monitor页面又能打开。用一段时间，线程就消耗完了。Monitor又打不开了。

**Comment by qct** [comment]
#110
