### ISSUE TITLE
monitor 模块空指针问题

### ISSUE THREAD

**Issue by BenZhang5779** [dubboclub/dubbokeeper#11]
Hi 
.
项目启动后，点击monitor报了空指针的问题。在UI Control 调用 statisticsStorage.queryApplications() 是返回出现了问题。请问下这个问题是配置出现了问题？ 还是需要启动其他的服务？多谢。

Error Log：
Caused by: java.lang.NullPointerException: null
    at com.dubboclub.dk.web.controller.MonitorController.monitorIndex(MonitorController.java:101) ~[classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
.
Thanks

**Comment by bieberHe** [comment]
暂时不要使用master分支，使用release分支

**Comment by BenZhang5779** [comment]
问题解决了 是dobbu的版本问题 Thanks
