### ISSUE TITLE
monitor 大盘信息无内容

### ISSUE THREAD

**Issue by harriks** [dubboclub/dubbokeeper#112]
应用监控大盘信息一致无法显示,
同样的配置在本机可以,但上传到服务器确一直无法显示,麻烦帮忙看看是哪里配置错了
在**mysql-dubbokeeper-server /conf/dubbo-mysql.properties**里配置
`dubbo.application.name=mysql-monitor
dubbo.application.owner=bieber
dubbo.registry.address=zookeeper://127.0.0.1:2181?backup=127.0.0.1:2182,127.0.0.1:2183
dubbo.protocol.name=dubbo
dubbo.protocol.port=20884

monitor.collect.interval=10000
#use netty4
dubbo.provider.transporter=netty4
#\u76D1\u63A7\u6570\u636E\u6301\u4E45\u5316\u5468\u671F,\u9ED8\u8BA4\u662F\u4E00\u5206\u949F,\u5355\u4F4D\u662F\u79D2
monitor.write.interval=60
#mysql
dubbo.monitor.mysql.url=jdbc:mysql://localhost:3306/dubbo-monitor
dubbo.monitor.mysql.username=root
dubbo.monitor.mysql.password=root
dubbo.monitor.mysql.pool.max=20
dubbo.monitor.mysql.pool.min=10
`

**在ui 的 dubbo.properties**
`dubbo.application.name=common-monitor
dubbo.application.owner=bieber
dubbo.registry.address=zookeeper://127.0.0.1:2181?backup=127.0.0.1:2182,127.0.0.1:2183

#use netty4
dubbo.reference.client=netty4

#peeper config
peeper.zookeepers=127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
peeper.zookeeper.session.timeout=60000

#logger
monitor.log.home=/home/harrik/server/tomcat/apache-tomcat-9.0.0/logs/monitor-log
monitor.collect.interval=6000`

另外除了这些配置哪里还能影响应用大盘展示的呢 谢谢

**Comment by qct** [comment]
有报错吗，错误信息日志贴一下

**Comment by harriks** [comment]
2017-05-17 11:44:15.422 [DubboSaveRegistryCache-thread-1] WARN  c.a.d.r.zookeeper.ZookeeperRegistry -  [DUBBO] Failed to save registry store file, cause: null, dubbo version: 2.5.3, current host: 192.168.100.5
java.nio.channels.OverlappingFileLockException: null
        at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255) ~[na:1.8.0_101]
        at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152) ~[na:1.8.0_101]
        at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108) ~[na:1.8.0_101]
        at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155) ~[na:1.8.0_101]
        at com.alibaba.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:191) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.registry.support.AbstractRegistry$SaveProperties.run(AbstractRegistry.java:150) [dubbo-2.5.3.jar:2.5.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

**Comment by qct** [comment]
把用户目录下  .dubbo文件夹里的文件清一下，重启 server
