### ISSUE TITLE
mysql-dubbokeeper-server启动出错。

### ISSUE THREAD

**Issue by linkexf** [dubboclub/dubbokeeper#124]
:23:29,576 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.dubboclub] to DEBUG
15:23:29,576 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [dkRolling] to Logger[com.dubboclub]
15:23:29,576 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:23:29,577 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@13a57a3b - Registering current configuration as safe fallback point

Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/core/OrderComparator$OrderSourceProvider
	at org.springframework.context.support.AbstractRefreshableApplicationContext.createBeanFactory(AbstractRefreshableApplicationContext.java:200)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:126)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:537)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:452)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.dubboclub.dk.server.Main.start(Main.java:39)
	at com.dubboclub.dk.server.Main.main(Main.java:29)
Caused by: java.lang.ClassNotFoundException: org.springframework.core.OrderComparator$OrderSourceProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

**Comment by qct** [comment]
看起来是spring 版本的问题。
