### ISSUE TITLE
lueneServer启动报错啊。

### ISSUE THREAD

**Issue by linzhiqiang0514** [dubboclub/dubbokeeper#33]
[NettyServerWorker-thread-1] WARN  2016-05-09 16:24:48313 com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:131)  -  [DUBBO] Skip input stream 435, dubbo version: 2.5.3, current host: 127.0.0.1
[DubboServerHandler-134.132.66.207:20884-thread-88] DEBUG 2016-05-09 16:24:48314 com.alibaba.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:60)  -  [DUBBO] Decode decodeable message com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation, dubbo version: 2.5.3, current host: 127.0.0.1
[NettyServerWorker-thread-1] WARN  2016-05-09 16:24:49319 com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:74)  -  [DUBBO] Decode rpc invocation failed: expected map/object at java.lang.String (Lcom/alibaba/dubbo/common/URL;), dubbo version: 2.5.3, current host: 127.0.0.1
com.alibaba.com.caucho.hessian.io.HessianProtocolException: expected map/object at java.lang.String (Lcom/alibaba/dubbo/common/URL;)
	at com.alibaba.com.caucho.hessian.io.AbstractDeserializer.error(AbstractDeserializer.java:108)
	at com.alibaba.com.caucho.hessian.io.AbstractMapDeserializer.readObject(AbstractMapDeserializer.java:70)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:1696)
	at com.alibaba.dubbo.common.serialize.support.hessian.Hessian2ObjectInput.readObject(Hessian2ObjectInput.java:94)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:119)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:71)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:137)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:126)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:87)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:46)
	at net.dubboclub.netty4.Netty4CodecAdapter$InternalDecoder.channelRead0(Netty4CodecAdapter.java:104)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
[NettyServerWorker-thread-1] WARN  2016-05-09 16:24:49320 com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:131)  -  [DUBBO] Skip input stream 435, dubbo version: 2.5.3, current host: 127.0.0.1

**Comment by linzhiqiang0514** [comment]
找到原因了。因为我应用用的而是dubbox。。。2.8.4。所以不兼容了。

**Comment by 654894017** [comment]
@linzhiqiang0514   我也用2.8.4 为嘛 开启服务监控就报错   
16:59:47.522 DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x1551f815ac0002a, packet:: clientPath:null serverPath:null finished:false header:: 38,8  replyHeader:: 38,939,0  request:: '/dubbo/com.alibaba.dubbo.monitor.MonitorService/routers,T  response:: v{} 
16:59:47.523 INFO  com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry -  [DUBBO] Notify urls for subscribe url consumer://192.168.0.108/com.alibaba.dubbo.monitor.MonitorService?category=providers,configurators,routers&dubbo=2.8.4&interface=com.alibaba.dubbo.monitor.MonitorService&pid=17392&timestamp=1465117182906, urls: [dubbo://192.168.0.108:20884/com.alibaba.dubbo.monitor.MonitorService?anyhost=true&application=mysql-monitor&dubbo=2.8.4&generic=false&interface=com.alibaba.dubbo.monitor.MonitorService&interval=10000&methods=lookup,collect&owner=bieber&pid=6320&revision=2.8.4&side=provider&timestamp=1465116607181, empty://192.168.0.108/com.alibaba.dubbo.monitor.MonitorService?category=configurators&dubbo=2.8.4&interface=com.alibaba.dubbo.monitor.MonitorService&pid=17392&timestamp=1465117182906, empty://192.168.0.108/com.alibaba.dubbo.monitor.MonitorService?category=routers&dubbo=2.8.4&interface=com.alibaba.dubbo.monitor.MonitorService&pid=17392&timestamp=1465117182906], dubbo version: 2.8.4, current host: 192.168.0.108
16:59:47.541 ERROR com.alibaba.dubbo.registry.integration.RegistryDirectory -  [DUBBO] Failed to refer invoker for interface:interface com.alibaba.dubbo.monitor.MonitorService,url:(dubbo://192.168.0.108:20884/com.alibaba.dubbo.monitor.MonitorService?anyhost=true&application=mysql-monitor&check=false&dubbo=2.8.4&generic=false&interface=com.alibaba.dubbo.monitor.MonitorService&interval=10000&methods=lookup,collect&owner=bieber&pid=17392&revision=2.8.4&side=provider&timestamp=1465117182906)org/jboss/netty/channel/ChannelFactory, dubbo version: 2.8.4, current host: 192.168.0.108
java.lang.NoClassDefFoundError: org/jboss/netty/channel/ChannelFactory
	at com.alibaba.dubbo.remoting.transport.netty.NettyTransporter.connect(NettyTransporter.java:37) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.remoting.Transporter$Adpative.connect(Transporter$Adpative.java) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.remoting.Transporters.connect(Transporters.java:67) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:224) [dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:195) [dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:449) [dubbo-2.8.4.jar:2.8.4]
net.dubboclub.netty4.help.RegistryFactoryNetty4Wrapper$RegistryWrapper.subscribe(RegistryFactoryNetty4Wrapper.java:71) [netty4-0.0.6.jar:0.0.6]

**Comment by linzhiqiang0514** [comment]
你是不是只替换了dubbo的包？不是通过maven替换的？

**Comment by 654894017** [comment]
@linzhiqiang0514   最早我是手动更新了包进去的不行   后边我在maven那边改成2.8.4也不行    moniterService这服务一直走netty3     自己写的服务都走netty4   我在配置文件中关闭服务监控，不会报这个错误 ，但是这样看不到监控的信息     有点没看明白为什么moniterService这个服务会一直走netty3

**Comment by linzhiqiang0514** [comment]
这个就不知道了，我这边目前是没有问题的




原始邮件
发件人:654894017notifications@github.com
收件人:dubboclub/dubbokeeperdubbokeeper@noreply.github.com
抄送:小强linzhiqiang0514@163.com; Mentionmention@noreply.github.com
发送时间:2016年6月6日(周一) 10:14
主题:Re: [dubboclub/dubbokeeper] lueneServer启动报错啊。 (#33)


@linzhiqiang0514 最早我是手动更新了包进去的不行 后边我在maven那边改成2.8.4也不行 moniterService这服务一直走netty3 自己写的服务都走netty4 我在配置文件中关闭服务监控，不会报这个错误 ，但是这样看不到监控的信息 有点没看明白为什么moniterService这个服务会一直走netty3

**Comment by 654894017** [comment]
@linzhiqiang0514  谢谢      你用的是2.5.4  netty3 还是netty4       我用2.5.4  netty4可以用

**Comment by linzhiqiang0514** [comment]
我这边是使用2.8.4 ，用的还是netty3


原始邮件
发件人:654894017notifications@github.com
收件人:dubboclub/dubbokeeperdubbokeeper@noreply.github.com
抄送:小强linzhiqiang0514@163.com; Mentionmention@noreply.github.com
发送时间:2016年6月6日(周一) 10:18
主题:Re: [dubboclub/dubbokeeper] lueneServer启动报错啊。 (#33)


@linzhiqiang0514 谢谢 你用的是2.5.4 netty3 还是netty4 我用2.5.4 netty4可以用
