### ISSUE TITLE
dubbox作为consumer端调用报错

### ISSUE THREAD

**Issue by rayzeng** [dubboclub/dubbokeeper#63]
consumer dubbo版本是2.8.4（dubbox），调用com.alibaba.dubbo.monitor.MonitorService.collect时异常，consumer切换回dubbo2.5.3正常调用。堆栈如下：
Exception in thread "main" com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method storeStatistics in the service com.dubboclub.dk.storage.StatisticsStorage. Tried 3 times of the providers [192.168.3.16:20884](1/1) from the registry 25.159.35.124:2381 on the consumer 192.168.3.16 using the dubbo version 2.8.4. Last error is: Failed to invoke remote method: storeStatistics, provider: dubbo://192.168.3.16:20884/com.dubboclub.dk.storage.StatisticsStorage?anyhost=true&application=consumer-of-helloworld-app&check=false&dubbo=2.8.4&generic=false&interface=com.dubboclub.dk.storage.StatisticsStorage&methods=storeStatistics,queryMethodMonitorOverview,queryApplicationOverview,queryStatisticsForMethod,queryApplications,queryApplicationInfo,queryServiceOverview,queryServiceByApp&owner=rayzeng&pid=17343&revision=1.0.1&side=consumer&timestamp=1472182317618, cause: Fail to decode request due to: RpcInvocation [methodName=storeStatistics, parameterTypes=[], arguments=null, attachments={path=com.dubboclub.dk.storage.StatisticsStorage, input=249, dubbo=2.8.4, version=0.0.0}]
    at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:108)
    at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:227)
    at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72)
    at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
    at com.alibaba.dubbo.common.bytecode.proxy0.storeStatistics(proxy0.java)
    at com.mor.client.dubbo.main.Main.statisticsStorage(Main.java:31)
    at com.mor.client.dubbo.main.Main.main(Main.java:15)
Caused by: com.alibaba.dubbo.remoting.RemotingException: Fail to decode request due to: RpcInvocation [methodName=storeStatistics, parameterTypes=[], arguments=null, attachments={path=com.dubboclub.dk.storage.StatisticsStorage, input=249, dubbo=2.8.4, version=0.0.0}]
    at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:190)
    at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:110)
    at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:84)
    at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:96)
    at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144)
    at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74)
    at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
    at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
    at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
    at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
    at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)
    ... 6 more

**Comment by bieberHe** [comment]
需要把项目中得dubbo得jar包替换成dubbox的，因为dubbox对协议做了调整

**Comment by zhangyq1011** [comment]
同样的错误、哈哈。通过以下修改就可了。
1.修改dubbo版本为 2.8.4
`
        
        <dubbo.version>2.8.4</dubbo.version>`
2、去掉dubbo对spring的依赖
`
                 <exclusion>
                 	<groupId>org.springframework</groupId>
     				 <artifactId>spring-beans</artifactId>
                 </exclusion>
			    <exclusion>
			      <groupId>org.springframework</groupId>
			      <artifactId>spring-core</artifactId>
			    </exclusion>
			    <exclusion>
			      <groupId>org.springframework</groupId>
			      <artifactId>spring-context</artifactId>
			    </exclusion>
			    <exclusion>
			      <groupId>org.springframework</groupId>
			      <artifactId>spring-aop</artifactId>
			    </exclusion>
			    <exclusion>
			      <groupId>org.springframework</groupId>
			      <artifactId>spring-expression</artifactId>
			    </exclusion>
			    <exclusion>
			    	<groupId>org.springframework</groupId>
  					<artifactId>spring-web</artifactId>
			    </exclusion>
			    `
3、显示添加其他spring的依赖
` 
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>${spring_version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aop</artifactId>
            <version>${spring_version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-expression</artifactId>
            <version>${spring_version}</version>
        </dependency>
		`
成功解决。

**Comment by zhangyq1011** [comment]
@rayzeng 你可以尝试以下、应该成功了。如果成功请 close 该issue 。
