### ISSUE TITLE
 应用大盘 没数据

### ISSUE THREAD

**Issue by wpf5788** [dubboclub/dubbokeeper#65]
下载的是git中的master中的程序

提供者和消费者中都添加了<dubbo:monitor protocol="registry"/>
server端也启动了，用的mysql，库和application也建了
ui端启动后没问题

消费都消费提供者都没问题  在ui端也能看到，ui中的zookeepr中也能看到

现在问题就是 应用大盘 没数据
关键是数据库中没数据  application表中也没数据，库中就一个application表，

另：版本用的2.8.4版本，ui和server都换成了2.8.4
请问下这是什么原因呢  我觉得关键是数据库中得有监视数据，ui才能展示出来，现在是数据库中一直没数据

**Comment by wpf5788** [comment]
Monitor-writer.log 表没数据 
DubboKeeper.log 表里面数据挺多的

**Comment by bieberHe** [comment]
有没有开启监控，dubbo.monitor.protocol=register

**Comment by ImDZ** [comment]
我这也是，monitor监控没数据，看了下ui调storage走rpc一直超时，时间设置长了也不行
`严重: Servlet.service() for servlet [springMVC] in context with path [] threw exception [Request processing failed; nested exception is com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method queryApplications in the service com.dubboclub.dk.storage.StatisticsStorage. Tried 3 times of the providers [10.1.84.41:20884] (1/1) from the registry 192.168.10.5:2181 on the consumer 10.1.84.41 using the dubbo version 2.5.3. Last error is: Invoke remote method timeout. method: queryApplications, provider: dubbo://10.1.84.41:20884/com.dubboclub.dk.storage.StatisticsStorage?anyhost=true&application=mysql-monitor&check=false&client=netty4&dubbo=2.5.3&interface=com.dubboclub.dk.storage.StatisticsStorage&logger=slf4j&methods=storeStatistics,queryMethodMonitorOverview,queryApplicationOverview,queryStatisticsForMethod,queryApplications,queryApplicationInfo,queryServiceOverview,queryServiceByApp&owner=bieber&pid=9977&revision=1.0.1&side=consumer&timestamp=1474368393980, cause: Sending request timeout in client-side by scan timer. start time: 2016-09-20 18:47:52.409, end time: 2016-09-20 18:47:53.411, elapsed: 1002 ms, timeout: 1000 ms, request: Request [id=2, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=queryApplications, parameterTypes=[], arguments=[], attachments={path=com.dubboclub.dk.storage.StatisticsStorage, interface=com.dubboclub.dk.storage.StatisticsStorage, version=0.0.0}]], channel: /10.1.84.41:62007 -> /10.1.84.41:20884] with root cause
com.alibaba.dubbo.remoting.TimeoutException: Sending request timeout in client-side by scan timer. start time: 2016-09-20 18:47:52.409, end time: 2016-09-20 18:47:53.411, elapsed: 1002 ms, timeout: 1000 ms, request: Request [id=2, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=queryApplications, parameterTypes=[], arguments=[], attachments={path=com.dubboclub.dk.storage.StatisticsStorage, interface=com.dubboclub.dk.storage.StatisticsStorage, version=0.0.0}]], channel: /10.1.84.41:62007 -> /10.1.84.41:20884
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:188)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:110)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:84)`

**Comment by ImDZ** [comment]
**严重: Servlet.service() for servlet [springMVC] in context with path [] threw exception [Request processing failed; nested exception is com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method queryApplications in the service com.dubboclub.dk.storage.StatisticsStorage. Tried 3 times of the providers [10.1.84.41:20884] (1/1) from the registry 192.168.10.5:2181 on the consumer 10.1.84.41 using the dubbo version 2.5.3. Last error is: Invoke remote method timeout. method: queryApplications, provider: dubbo://10.1.84.41:20884/com.dubboclub.dk.storage.StatisticsStorage?anyhost=true&application=mysql-monitor&check=false&client=netty4&dubbo=2.5.3&interface=com.dubboclub.dk.storage.StatisticsStorage&logger=slf4j&methods=storeStatistics,queryMethodMonitorOverview,queryApplicationOverview,queryStatisticsForMethod,queryApplications,queryApplicationInfo,queryServiceOverview,queryServiceByApp&owner=bieber&pid=9977&revision=1.0.1&side=consumer&timestamp=1474368393980, cause: Sending request timeout in client-side by scan timer. start time: 2016-09-20 18:47:52.409, end time: 2016-09-20 18:47:53.411, elapsed: 1002 ms, timeout: 1000 ms, request: Request [id=2, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=queryApplications, parameterTypes=[], arguments=[], attachments={path=com.dubboclub.dk.storage.StatisticsStorage, interface=com.dubboclub.dk.storage.StatisticsStorage, version=0.0.0}]], channel: /10.1.84.41:62007 -> /10.1.84.41:20884] with root cause
com.alibaba.dubbo.remoting.TimeoutException: Sending request timeout in client-side by scan timer. start time: 2016-09-20 18:47:52.409, end time: 2016-09-20 18:47:53.411, elapsed: 1002 ms, timeout: 1000 ms, request: Request [id=2, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=queryApplications, parameterTypes=[], arguments=[], attachments={path=com.dubboclub.dk.storage.StatisticsStorage, interface=com.dubboclub.dk.storage.StatisticsStorage, version=0.0.0}]], channel: /10.1.84.41:62007 -> /10.1.84.41:20884
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:188)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:110)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:84)**

**Comment by ImDZ** [comment]
> 严重: Servlet.service() for servlet [springMVC] in context with path [] threw exception [Request processing failed; nested exception is com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method queryApplications in the service com.dubboclub.dk.storage.StatisticsStorage. Tried 3 times of the providers [10.1.84.41:20884] (1/1) from the registry 192.168.10.5:2181 on the consumer 10.1.84.41 using the dubbo version 2.5.3. Last error is: Invoke remote method timeout. method: queryApplications, provider: dubbo://10.1.84.41:20884/com.dubboclub.dk.storage.StatisticsStorage?anyhost=true&application=mysql-monitor&check=false&client=netty4&dubbo=2.5.3&interface=com.dubboclub.dk.storage.StatisticsStorage&logger=slf4j&methods=storeStatistics,queryMethodMonitorOverview,queryApplicationOverview,queryStatisticsForMethod,queryApplications,queryApplicationInfo,queryServiceOverview,queryServiceByApp&owner=bieber&pid=9977&revision=1.0.1&side=consumer&timestamp=1474368393980, cause: Sending request timeout in client-side by scan timer. start time: 2016-09-20 18:47:52.409, end time: 2016-09-20 18:47:53.411, elapsed: 1002 ms, timeout: 1000 ms, request: Request [id=2, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=queryApplications, parameterTypes=[], arguments=[], attachments={path=com.dubboclub.dk.storage.StatisticsStorage, interface=com.dubboclub.dk.storage.StatisticsStorage, version=0.0.0}]], channel: /10.1.84.41:62007 -> /10.1.84.41:20884] with root cause
com.alibaba.dubbo.remoting.TimeoutException: Sending request timeout in client-side by scan timer. start time: 2016-09-20 18:47:52.409, end time: 2016-09-20 18:47:53.411, elapsed: 1002 ms, timeout: 1000 ms, request: Request [id=2, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=queryApplications, parameterTypes=[], arguments=[], attachments={path=com.dubboclub.dk.storage.StatisticsStorage, interface=com.dubboclub.dk.storage.StatisticsStorage, version=0.0.0}]], channel: /10.1.84.41:62007 -> /10.1.84.41:20884
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:188)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:110)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:84)

**Comment by ImDZ** [comment]
_严重: Servlet.service() for servlet [springMVC] in context with path [] threw exception [Request processing failed; nested exception is com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method queryApplications in the service com.dubboclub.dk.storage.StatisticsStorage. Tried 3 times of the providers [10.1.84.41:20884] (1/1) from the registry 192.168.10.5:2181 on the consumer 10.1.84.41 using the dubbo version 2.5.3. Last error is: Invoke remote method timeout. method: queryApplications, provider: dubbo://10.1.84.41:20884/com.dubboclub.dk.storage.StatisticsStorage?anyhost=true&application=mysql-monitor&check=false&client=netty4&dubbo=2.5.3&interface=com.dubboclub.dk.storage.StatisticsStorage&logger=slf4j&methods=storeStatistics,queryMethodMonitorOverview,queryApplicationOverview,queryStatisticsForMethod,queryApplications,queryApplicationInfo,queryServiceOverview,queryServiceByApp&owner=bieber&pid=9977&revision=1.0.1&side=consumer&timestamp=1474368393980, cause: Sending request timeout in client-side by scan timer. start time: 2016-09-20 18:47:52.409, end time: 2016-09-20 18:47:53.411, elapsed: 1002 ms, timeout: 1000 ms, request: Request [id=2, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=queryApplications, parameterTypes=[], arguments=[], attachments={path=com.dubboclub.dk.storage.StatisticsStorage, interface=com.dubboclub.dk.storage.StatisticsStorage, version=0.0.0}]], channel: /10.1.84.41:62007 -> /10.1.84.41:20884] with root cause
com.alibaba.dubbo.remoting.TimeoutException: Sending request timeout in client-side by scan timer. start time: 2016-09-20 18:47:52.409, end time: 2016-09-20 18:47:53.411, elapsed: 1002 ms, timeout: 1000 ms, request: Request [id=2, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=queryApplications, parameterTypes=[], arguments=[], attachments={path=com.dubboclub.dk.storage.StatisticsStorage, interface=com.dubboclub.dk.storage.StatisticsStorage, version=0.0.0}]], channel: /10.1.84.41:62007 -> /10.1.84.41:20884
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:188)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:110)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:84)_

**Comment by bieberHe** [comment]
后端服务有没有部署起来，部署了几台服务端

**Comment by ImDZ** [comment]
后端服务起来了，服务端就部署了一台，折腾了两天，就出来过一次数据 - -！

**Comment by bieberHe** [comment]
你当前的dubbo集群是多少？如果太多，可能一台服务器扛不住

**Comment by zhangyq1011** [comment]
貌似是因为dubbo的版本引起的。我这边的错误是：
`Caused by: com.alibaba.dubbo.remoting.RemotingException: Fail to decode request due to: RpcInvocation [methodName=collect, parameterTypes=[], arguments=null, attachments={dubbo=2.8.4, input=720, path=com.alibaba.dubbo.monitor.MonitorService, version=0.0.0}]
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:190)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:110)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:84)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:96)
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144)
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)
	... 13 more`
dubbokeeper 使用dubbo版本为：2.5.3

应用实例使用dubbo版本为：2.8.4

**Comment by dongc** [comment]
@bieberHe 你好！应用大盘中仅有“common-monitor”数据，没有其他数据。怎么配置啊？对象

**Comment by qct** [comment]
@dongc 你的后端服务(dubbokeeper-server) 没有起来

**Comment by dongc** [comment]
启动了

**Comment by dongc** [comment]
应用大盘中 仅有一个“ common-monitor”

**Comment by qct** [comment]
@dongc 你启动的是dubbokeeper-ui， 还要再启动dubbokeeper-server，才能收集数据

**Comment by dongc** [comment]
一个mysql-dubbokeeper-server 一个mysql-dubbokeeper-ui

**Comment by dongc** [comment]
@qct 方便的话，QQ指点一下：494988600

**Comment by qct** [comment]
你可以贴一下dubbokeeper-server启动的日志吗？ 在logback.xml里面 把stdout开到debug，另外再贴一下你的 dubbo-mysql.properties配置

**Comment by dongc** [comment]
@qct 帮看一下我的配置：
ubbo.application.name=mysql-monitor
dubbo.application.owner=bieber
# 130 186
dubbo.registry.address=zookeeper://*** *** ***:2181
dubbo.protocol.name=dubbo
dubbo.protocol.port=20884

monitor.collect.interval=10000
#usered netty4
dubbo.provider.transporter=netty4
#监控数据持久化周期,默认是一分钟,单位是秒
monitor.write.interval=60
#mysql
dubbo.monitor.mysql.url=jdbc:mysql://192.168.188.101:3306/dubbokeeper
dubbo.monitor.mysql.username=root
dubbo.monitor.mysql.password=123456
dubbo.monitor.mysql.pool.max=10
dubbo.monitor.mysql.pool.min=10

**Comment by qct** [comment]
`ubbo.application.name=mysql-monitor`
应该是  
`dubbo.application.name=mysql-monitor`

是你手滑贴错了还是配置文件就是这么配的？

如果用了zookeeper，那zookeeper地址也要配上。

**Comment by leizime** [comment]
解决了吗？我也碰到这问题？

**Comment by SpringStudent** [comment]
我也是应用大盘什么数据都没有

**Comment by EricBatty** [comment]
我也碰到了这个问题，请问大家怎么弄的

**Comment by EricBatty** [comment]
@qct 你好,
